---
# Filter settings
fs: 2500
f_theta_lower: 4
f_theta_upper: 12
f_lowpass: 25
lowpass_length: 0.5  # could be changed to 0.1
bandpass_length: 0.75

#Cycle-by-cycle algorithm threshold settings 
threshold_bycycle: 
  amp_fraction_threshold:       0.8
  amp_consistency_threshold:    0
  period_consistency_threshold: 0
  monotonicity_threshold:       0
  min_n_cycles:                 8

#Episodic threshold settings
threshold_episode: 2500
